/* Generated By:JavaCC: Do not edit this line. AntBrainParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AntBrainParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SENSE = 2;
  /** RegularExpression Id. */
  int MARK = 3;
  /** RegularExpression Id. */
  int UNMARK = 4;
  /** RegularExpression Id. */
  int PICKUP = 5;
  /** RegularExpression Id. */
  int DROP = 6;
  /** RegularExpression Id. */
  int TURN = 7;
  /** RegularExpression Id. */
  int MOVE = 8;
  /** RegularExpression Id. */
  int FLIP = 9;
  /** RegularExpression Id. */
  int HERE = 10;
  /** RegularExpression Id. */
  int AHEAD = 11;
  /** RegularExpression Id. */
  int LEFTAHEAD = 12;
  /** RegularExpression Id. */
  int RIGHTAHEAD = 13;
  /** RegularExpression Id. */
  int FRIEND = 14;
  /** RegularExpression Id. */
  int FOE = 15;
  /** RegularExpression Id. */
  int FRIENDWITHFOOD = 16;
  /** RegularExpression Id. */
  int FOEWITHFOOD = 17;
  /** RegularExpression Id. */
  int FOOD = 18;
  /** RegularExpression Id. */
  int ROCK = 19;
  /** RegularExpression Id. */
  int MARKER = 20;
  /** RegularExpression Id. */
  int FOEMARKER = 21;
  /** RegularExpression Id. */
  int HOME = 22;
  /** RegularExpression Id. */
  int FOEHOME = 23;
  /** RegularExpression Id. */
  int LEFT = 24;
  /** RegularExpression Id. */
  int RIGHT = 25;
  /** RegularExpression Id. */
  int I = 26;
  /** RegularExpression Id. */
  int STATE = 27;
  /** RegularExpression Id. */
  int COMMENT = 28;
  /** RegularExpression Id. */
  int RETURN = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"Sense\"",
    "\"Mark\"",
    "\"Unmark\"",
    "\"PickUp\"",
    "\"Drop\"",
    "\"Turn\"",
    "\"Move\"",
    "\"Flip\"",
    "\"Here\"",
    "\"Ahead\"",
    "\"LeftAhead\"",
    "\"RightAhead\"",
    "\"Friend\"",
    "\"Foe\"",
    "\"FriendWithFood\"",
    "\"FoeWithFood\"",
    "\"Food\"",
    "\"Rock\"",
    "\"Marker\"",
    "\"FoeMarker\"",
    "\"Home\"",
    "\"FoeHome\"",
    "\"Left\"",
    "\"Right\"",
    "<I>",
    "<STATE>",
    "<COMMENT>",
    "\"\\n\"",
  };

}
